export type DocSection = { id: string; title: string; paragraphs?: string[]; steps?: string[]; code?: { language: string; value: string }; links?: { label: string; slug: string }[] }
export type DocPage = { slug: string; group: 'Start here' | 'Build and operate' | 'Reference'; title: string; description: string; sections: DocSection[] }
export const docs: DocPage[] = [
  { slug: 'introduction', group: 'Start here', title: 'Meet Kernel', description: 'A shared foundation for business applications that people and agents can use.', sections: [
    { id: 'one-application', title: 'One application. Two ways to work.', paragraphs: ['Kernel provides the structure and runtime for business applications such as CRM, project management, purchasing, and support. A published definition gives people forms, queues, and actions. It gives agents structured contracts for querying records and proposing or executing authorized operations.', 'The same runtime validates both paths. Identity, permissions, policies, record versions, and relationships are checked by the server. A model can suggest work; it cannot grant itself permission.'] },
    { id: 'build-operate-evolve', title: 'Build, operate, evolve', steps: ['Build an application from catalog modules, or use an external builder agent to submit a validated custom definition.', 'Preview and publish the definition. Publication creates the application without copying preview records into live data.', 'Give an operating agent a scoped credential. Review its proposals or explicitly grant automatic execution for selected operations.', 'Revise a published application through a draft and a migration preview. Compatible additions can be published with version checks.'], links: [{ label: 'Build your first application', slug: 'build-applications' }] },
    { id: 'who-it-is-for', title: 'For builders and the teams they support', paragraphs: ['Kernel is for developers and agent builders who need reusable business software primitives, and for operations teams who will use the resulting applications. CRM and team issues are reference applications for this foundation.', 'Kernel is under active development. It is not an arbitrary code generator or a complete enterprise platform. Start with synthetic data and evaluate it against your workflow.'], links: [{ label: 'Read the current scope', slug: 'current-scope' }, { label: 'Start locally', slug: 'quickstart' }] },
  ] },
  { slug: 'quickstart', group: 'Start here', title: 'Run Kernel locally', description: 'Start a workspace, explore a sample application, and publish your own.', sections: [
    { id: 'requirements', title: 'Prepare your checkout', paragraphs: ['Use a checkout of the Kernel repository with Node.js 22.12 or later and pnpm 9.14.2. Run these commands from the repository root. Local development uses embedded PostgreSQL through PGlite.'], code: { language: 'sh', value: 'pnpm install\npnpm setup\npnpm dev' } },
    { id: 'create-workspace', title: 'Create your workspace', steps: ['Open http://localhost:3000 and choose Open workspace, then create an account.', 'Use the local KERNEL_SIGNUP_CODE from .env. Setup generates it when needed; treat it as an invitation secret.', 'Explore the labeled purchasing demo. It contains sample records. Your subsequently published applications start without preview data.'], paragraphs: ['Setup creates a local authentication secret and preserves existing environment values. Signup is refused if KERNEL_SIGNUP_CODE is missing. Never commit your .env or share its secrets in public documentation.'] },
    { id: 'publish-first-app', title: 'Publish an application', steps: ['Open Applications and choose Create application.', 'Choose a catalog pattern such as CRM or team issues, inspect its modules and preview, then publish.', 'Create a real record in the new application. Open Configure → Agents when you are ready to connect an operating agent.'], links: [{ label: 'Understand the building blocks', slug: 'concepts' }, { label: 'Connect an external agent', slug: 'connect-agents' }] },
    { id: 'model-optional', title: 'A connected model is optional', paragraphs: ['Catalog assembly works without a model API key. Natural-language planning and the application assistant require a compatible provider configured on the server.'], links: [{ label: 'Configure the model provider', slug: 'model-configuration' }] },
  ] },
  { slug: 'concepts', group: 'Start here', title: 'Core concepts', description: 'The vocabulary behind an application, its interface, and its agent contract.', sections: [
    { id: 'application', title: 'Workspace, application, entity', paragraphs: ['A workspace is the tenant boundary. An application—also called a project—owns a set of entity capabilities. An entity defines fields, lifecycle states, actions, and policies. Records are versioned instances of those entities.', 'Relationships reference record IDs in another entity within the same application and workspace. They are validated references, not arbitrary database joins.'] },
    { id: 'composition', title: 'Modules, patterns, and assemblies', paragraphs: ['A module is a reusable catalog unit with business objects, links, actions, and bound surfaces. Modules declare versions and dependencies. A pattern is a starting composition such as CRM, purchasing, or team issues.', 'An assembly selects modules, settings, links, and surfaces. Kernel compiles it into a validated application definition. External builder agents can also submit custom definitions within the supported contract.'] },
    { id: 'presentation', title: 'Blocks and grammars', paragraphs: ['Blocks are generic presentation units such as tables, boards, record cards, filters, stats, and charts. A grammar selects a working layout and density for a surface. Presentation uses the same entity definitions as agent discovery.', 'A catalog listing does not always mean a block has an execution runtime: chat and email blocks are currently listed without one.'] },
    { id: 'changes', title: 'Drafts, proposals, and runs', paragraphs: ['A draft proposes an application definition. Publishing it changes the application structure. A proposal, or ChangeSet, proposes an operational record change. Applying it changes business data.', 'A run is a durable sequence of up to 25 operations. It can reference a record created by an earlier step, pause for review, and resume from its saved checkpoint. Each applied operation retains its audit attribution.'], links: [{ label: 'Operate with agents', slug: 'agent-runs' }] },
  ] },
  { slug: 'build-applications', group: 'Build and operate', title: 'Build an application', description: 'Compose a catalog app or author a supported definition through an external builder.', sections: [
    { id: 'catalog', title: 'Start from a catalog pattern', paragraphs: ['Kernel includes purchasing, CRM, team-issues, payments, and support patterns. Choose one in the application builder, inspect the assembly and sample preview, then publish.', 'The connected built-in planner helps select catalog modules and settings from a business brief. It does not invent arbitrary entity schemas or generate executable application code.'] },
    { id: 'external-builder', title: 'Build through MCP', steps: ['As a workspace owner, create a builder credential from Agents.', 'Connect an MCP client to /api/mcp with the credential in an Authorization bearer header.', 'Call get_application_contract for supported schema and limits, or list_patterns and list_modules for catalog composition.', 'Call save_draft with a pattern, assembly, or definition. Inspect the draft before publish_draft.'], paragraphs: ['Builder credentials are workspace-wide and can publish definitions. Operating credentials cannot publish. Keep those responsibilities separate.'], links: [{ label: 'Credential setup and discovery', slug: 'connect-agents' }] },
    { id: 'evolution', title: 'Evolve a published application', steps: ['Open Configure → Change application, or call edit_project with a builder credential.', 'Save a revision and generate a migration preview against current records.', 'Review the proposed changes, then publish the expected draft version with its preview token.'], paragraphs: ['Supported changes include compatible entity/field additions, label and policy changes, and explicit defaults for missing values. Stale previews and incompatible changes are rejected. Field removal, type changes, relationship retargeting, and automatic rollback are not supported.'] },
  ] },
  { slug: 'connect-agents', group: 'Build and operate', title: 'Connect an agent', description: 'Use scoped credentials to discover application contracts over MCP or HTTP.', sections: [
    { id: 'credentials', title: 'Choose the credential kind', paragraphs: ['Builder credentials create and evolve applications. Create them from the workspace Agents page. Operate credentials query a published application and use its selected operations. Create them in that application’s Configure → Agents page.', 'Operate grants pin selected actions to capability versions. They can read the application’s records, not just fields used by an action. Credentials expire after 1–90 days and can be revoked. Their secret is shown once.'] },
    { id: 'mcp', title: 'Connect over MCP', paragraphs: ['Use your Kernel origin followed by /api/mcp. The server supports Streamable HTTP. Configure Authorization: Bearer with your credential in a client that supports bearer headers. OAuth onboarding is not available.', 'The credential determines the tool set. Builders discover the application contract and manage drafts. Operating agents discover records and scoped tools, stage proposals, and manage durable runs. Never use a human session cookie as an agent credential.'] },
    { id: 'http', title: 'Discover with HTTP', paragraphs: ['Operate credentials also work at /api/agent. Discovery returns project metadata, capabilities, scoped tools, records, a cursor, and stale actions. Follow nextCursor to continue. Replace the example origin and set KERNEL_AGENT_TOKEN in your shell without committing it.'], code: { language: 'sh', value: 'curl https://YOUR_KERNEL_HOST/api/agent \\\n  -H "Authorization: Bearer $KERNEL_AGENT_TOKEN"' } },
    { id: 'stage', title: 'Propose an operation', paragraphs: ['Choose an action and record returned by discovery. Fill input from its schema and send the request to /api/agent. This body is a template: replace the example IDs and action with discovered values. Staging does not apply the change.'], code: { language: 'json', value: '{\n  "type": "stage",\n  "recordId": "RECORD_FROM_DISCOVERY",\n  "action": "ACTION_FROM_DISCOVERY",\n  "input": {},\n  "idempotencyKey": "task-001-operation-001"\n}' }, links: [{ label: 'Review, execute, and recover runs', slug: 'agent-runs' }] },
    { id: 'renew', title: 'Handle changes to access', paragraphs: ['After a definition changes, the owner must review and reissue affected grants. Expiry, revocation, and loss of the issuing owner’s access block future use and applying pending proposals. Owners can still reject them.', 'Reuse the same request key and body after a transport failure. Changing a request under the same key produces an idempotency conflict. Bearer credentials are accepted at /api/agent and /api/mcp, not the human-session /api/kernel endpoint.'] },
  ] },
  { slug: 'agent-runs', group: 'Build and operate', title: 'Operate and review runs', description: 'Give agents bounded work, inspect the evidence, and recover from interruptions.', sections: [
    { id: 'review', title: 'Review is the default', paragraphs: ['Stage tools create proposals for human review. The server rechecks authorization, record and definition versions, business rules, and references when a proposal is applied.', 'An owner can explicitly grant automatic execution for selected operations. Separate execute tools use the same validation and transaction path. The built-in assistant also requires automatic execution to be enabled for the particular task.'] },
    { id: 'assistant', title: 'Use the application assistant', steps: ['Open an application as an owner and choose a scoped operating credential in the assistant.', 'Describe a bounded task. The planner can query records and save a sequence of supported operations.', 'Inspect recent runs to see step inputs, proposed changes, outcomes, and history.', 'Review pending proposals in Inbox. Approved steps allow the worker to continue; rejected proposals require a revised task.'] },
    { id: 'durable', title: 'Start and manage durable work', paragraphs: ['Use start_run with an idempotency key and 1–25 steps. Each step names create or action, a capability, business input, and review or automatic execution. Action steps name an existing record or {step: 0} to reference an earlier step’s record.', 'Use manage_run with runId and get, advance, cancel, or retry. Retry resumes a recoverable failure from the saved step. Cancellation rejects pending proposals and prevents later steps; already-applied changes remain.'], code: { language: 'json', value: '{\n  "type": "manage_run",\n  "runId": "RUN_ID",\n  "command": "get"\n}' } },
    { id: 'limits', title: 'Built-in bounds', paragraphs: ['Each credential can have five queued or review-waiting runs and create 60 new operation proposals per rolling minute. Replays do not consume another operation. Rate-limited run steps stay queued.', 'Runs expire seven days after creation, including human review time. The worker rejects outstanding proposals when it processes expiry; an overdue proposal cannot be applied while the worker is offline.', 'The embedded planner allows one live request per credential, three provider calls per task across retries, and 30 calls per rolling hour per credential. Each attempt has a five-minute deadline, a 200 KB context limit, and a 4,096-token output cap. These bounds do not guarantee a specific currency spend.'] },
    { id: 'worker', title: 'Check the worker', paragraphs: ['The local Node runtime polls runs in the background. A dedicated worker can be started with pnpm worker. Run inspection shows queued runs with no update for 60 seconds as stalled; waiting for a human is not a stall.', 'Owner-visible health reports recent successful and failed polls. An active heartbeat does not mean every task succeeded. Cloudflare requires a dedicated operation worker or explicit advancement; automatic operation scheduling is not included.'], links: [{ label: 'Deployment and maintenance', slug: 'deployment' }] },
  ] },
  { slug: 'model-configuration', group: 'Reference', title: 'Model configuration', description: 'Connect the optional server-side planner to a compatible provider.', sections: [
    { id: 'configure', title: 'Configure the server', paragraphs: ['Set a provider API key, model ID, and Responses-compatible API root in the server environment, then restart. The API root must not include /responses; Kernel appends it. Credentials stay on the server.', 'The following values are placeholders. Use an endpoint and model supported by your provider. KERNEL_API_KEY takes precedence over the legacy OPENAI_API_KEY fallback.'], code: { language: 'dotenv', value: 'KERNEL_API_BASE_URL="https://YOUR_PROVIDER_API_ROOT"\nKERNEL_API_KEY="YOUR_PROVIDER_KEY"\nKERNEL_MODEL="YOUR_SUPPORTED_MODEL"\nKERNEL_MODEL_TIMEOUT_MS="300000"' } },
    { id: 'compatibility', title: 'Check protocol compatibility', paragraphs: ['The adapter expects a synchronous Responses API with JSON-object output. A service offering only Chat Completions is not enough. Kernel validates output against the supported schemas; malformed responses never grant additional capabilities.', 'KERNEL_REASONING_EFFORT is optional and provider-dependent. Leave it unset unless your selected model supports it. Provider availability and output budgets vary; test the exact configuration you intend to deploy.'] },
    { id: 'timeouts', title: 'Understand the request budget', paragraphs: ['The general request timeout defaults to five minutes and accepts 1,000–900,000 milliseconds. Embedded operation planning has its own five-minute attempt deadline and a durable call budget. Increasing the general timeout does not extend that operation deadline.', 'After interruption, retry the same task key. Attempted calls still count against its budget. Do not assume a disconnected request was free.'], links: [{ label: 'Operation limits and recovery', slug: 'agent-runs' }] },
  ] },
  { slug: 'deployment', group: 'Reference', title: 'Deployment and maintenance', description: 'Prepare persistence, authentication, model settings, and workers for your environment.', sections: [
    { id: 'runtime', title: 'Choose a runtime and database', paragraphs: ['Local Node development defaults to PGlite. For a PostgreSQL server, set KERNEL_PGLITE=0 and configure DATABASE_URL. Persistent storage and backups are deployment responsibilities.', 'Cloudflare uses Workers and PostgreSQL through Hyperdrive. Follow the repository’s docs/CLOUDFLARE.md for bindings, environment values, and deployment commands. Cloudflare deployment is not covered by the current local acceptance evidence.'] },
    { id: 'auth', title: 'Set authentication deliberately', paragraphs: ['Set BETTER_AUTH_URL to your application origin, a strong BETTER_AUTH_SECRET, and KERNEL_SIGNUP_CODE for controlled signup. Use HTTPS for remote deployments. Keep model and agent credentials out of source control and client-side code.'] },
    { id: 'migrations', title: 'Apply migrations before restart', paragraphs: ['For server PostgreSQL, deploy repository migrations and regenerate Prisma before restarting web and worker processes. Embedded PGlite applies pending migrations through the database opener. Back up data before deployment.'], code: { language: 'sh', value: 'pnpm exec prisma migrate deploy\npnpm db:generate\npnpm build' } },
    { id: 'operations', title: 'Run operations and observe health', paragraphs: ['Start the long-lived worker where appropriate with pnpm worker. It polls application builds and operation runs. The Node web runtime also starts local pollers; checkpoints protect against competing workers.', 'Inspect worker logs, failed runs, and owner-visible heartbeat status. Cloudflare construction workflows do not automatically schedule operation runs. Model-call reservations are retained; production retention and cleanup require separate planning.'], links: [{ label: 'Current validation and limitations', slug: 'current-scope' }] },
  ] },
  { slug: 'current-scope', group: 'Reference', title: 'Current scope', description: 'What Kernel supports today, and the boundaries to plan around.', sections: [
    { id: 'supported', title: 'Available today', paragraphs: ['Catalog composition and validated custom definitions, generated human interfaces, scoped MCP/HTTP tools, reviewed record creation and actions, explicitly granted automatic operations, durable runs, audit history, compatible application evolution, and resource limits.', 'Definitions support 1–8 entities with string, integer, boolean, and enum fields. Relationships are validated record references. Policies support a constrained rule language; definitions do not execute arbitrary code or SQL.'] },
    { id: 'boundaries', title: 'Boundaries', paragraphs: ['There are no arbitrary external integrations, cross-record policy evaluation, relationship joins, destructive schema migrations, data rollback, field-level permissions, or OAuth agent onboarding. Listed chat/email blocks do not have an operational runtime.', 'The built-in builder selects from catalog modules. More general supported definitions are authored through the external builder contract. A saved view is not a general query language.'] },
    { id: 'evidence', title: 'Validation is still ongoing', paragraphs: ['The repository includes isolated database tests and synthetic CRM and project workflows. Live-provider and signed-in synthetic journeys have been exercised for specific configurations. That does not establish broad provider compatibility or real-user acceptance.', 'The latest resource-limit changes passed local automated checks. Live-provider validation of the tighter output cap, browser verification of the latest inspector/health additions, real-operator trials, and production deployment verification remain outstanding. No customer testimonials or production reliability claims are implied.'], links: [{ label: 'Get started with a local evaluation', slug: 'quickstart' }] },
  ] },
]
export function findDoc(slug: string) { return docs.find(page => page.slug === slug) }
export function searchDocs(query: string) {
  const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean)
  return docs.filter(page => { const text = `${page.title} ${page.description} ${page.sections.map(s => [s.title, ...(s.paragraphs ?? []), ...(s.steps ?? [])].join(' ')).join(' ')}`.toLowerCase(); return terms.every(term => text.includes(term)) })
}
