import { validateApplication } from '../../src/kernel/application'
import { crm } from '../../src/kernel/suite'

/** Authored synthetic definition: exercises the generic builder, not model generation. */
export function crmAcceptanceApplication() {
  return validateApplication({
    name: 'QA Sales workspace',
    description: 'Synthetic acceptance application for lead qualification and reviewed conversion.',
    assumptions: ['Authored QA definition, not generated by a live model. All records used for this acceptance journey are synthetic.'],
    entities: [crm],
    navigation: [{ entity: 'crm', label: 'Sales pipeline' }],
    views: [
      { id: 'open_leads', name: 'Open leads', entity: 'crm', filters: [{ field: 'status', operator: 'eq', value: 'open' }], sort: { field: 'title', direction: 'asc' }, columns: ['title', 'company', 'status'] },
      { id: 'customers', name: 'Converted leads', entity: 'crm', filters: [{ field: 'status', operator: 'eq', value: 'converted' }], sort: { field: 'title', direction: 'asc' }, columns: ['title', 'company', 'status'] },
    ],
    startView: null,
    layouts: [{ entity: 'crm', sections: [
      { id: 'contact', name: 'Contact details', fields: ['title', 'company', 'contact', 'source'] },
      { id: 'progress', name: 'Pipeline progress', fields: ['status'], when: { field: 'status', operator: 'neq', value: 'draft' } },
    ] }],
  })
}
